version: '3.3'
volumes:
  data:
services:
  web:
    image: nginx:latest
    container_name: nginx-app
    restart: always
    ports: 
      - 3000:80
    volumes:
      - .:/var/www/app
      - ./docker_config/nginx/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      dockerfile: ./docker_config/php/php7-dockerfile
      context: .
      args:
        - "UID=$UID"
        - "GID=$GID"
        - "USER=$USER"
    image: php7-dockerfile
    container_name: php-app
    volumes:
      - .:/var/www/app
    # links:
    #   - db
  # db:
  #   image: mysql:5.7
  #   container_name: mysql-app
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=dev
  #     - MYSQL_DATABASE=livros_db
  #     - TZ=America/Sao_Paulo
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db:db
  #   ports:
  #     - "8082:80"
  #   environment:
  #     - PMA_USER=root
  #     - PMA_PASSWORD=dev
  #     - PHP_UPLOAD_MAX_FILESIZE=500MB